version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /supervisor
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directories:
      - /modules/aws
      - /modules/azure
      - /modules/gcp
      - /examples/aws
      - /examples/azure
      - /examples/gcp
    schedule:
      interval: weekly
    groups:
      providers:
        patterns: ['*']
  - package-ecosystem: gomod
    directory: /tests/crd-validation
    schedule:
      interval: weekly
    groups:
      kubernetes:
        patterns: ['k8s.io/*']
