apiVersion: v1
kind: Service
metadata:
  name: {{ include "instruction-hub-worker.fullname" . }}
  labels:
    {{- include "instruction-hub-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: analyzer
    app.kubernetes.io/name: {{ include "instruction-hub-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.workerPort }}
      targetPort: http
